port: 3001
timeout: 120000
services:
  sptribs:
    url: 'http://localhost:4013'
  ccd:
    url: 'http://localhost:4452'
  cdam:
    url: 'http://localhost:4455'
  feeLookup:
    url: 'http://fees-register-api-aat.service.core-compute-aat.internal/fees-register/fees/lookup'
  dssUpdate:
    url: 'http://localhost:3100'
  equalityAndDiversity:
    enabled: true
queryParamsforApp:
  query:
    FMP: 'FMPO'
    RLAD: 'RELADOP'
    FGM: 'FGM'
